// declare const enum MyShuriKenParticle3DConstant {
//     WORLDPOSITION = 0,
//     WORLDROTATION = 1,
//     POSITIONSCALE = 4,//TODO:是否可以从2开始
//     SIZESCALE = 5,
//     SCALINGMODE = 6,
//     GRAVITY = 7,
//     THREEDSTARTROTATION = 8,
//     STRETCHEDBILLBOARDLENGTHSCALE = 9,
//     STRETCHEDBILLBOARDSPEEDSCALE = 10,
//     SIMULATIONSPACE = 11,
//     CURRENTTIME = 12,
//
//     //VelocityOverLifetime
//     VOLVELOCITYCONST = 13,
//     VOLVELOCITYGRADIENTX = 14,
//     VOLVELOCITYGRADIENTY = 15,
//     VOLVELOCITYGRADIENTZ = 16,
//     VOLVELOCITYCONSTMAX = 17,
//     VOLVELOCITYGRADIENTXMAX = 18,
//     VOLVELOCITYGRADIENTYMAX = 19,
//     VOLVELOCITYGRADIENTZMAX = 20,
//     VOLSPACETYPE = 21,
//
//     //ColorOverLifetime
//     COLOROVERLIFEGRADIENTALPHAS = 22,
//     COLOROVERLIFEGRADIENTCOLORS = 23,
//     MAXCOLOROVERLIFEGRADIENTALPHAS = 24,
//     MAXCOLOROVERLIFEGRADIENTCOLORS = 25,
//
//     //SizeOverLifetime
//     SOLSIZEGRADIENT = 26,
//     SOLSIZEGRADIENTX = 27,
//     SOLSIZEGRADIENTY = 28,
//     SOLSizeGradientZ = 29,
//     SOLSizeGradientMax = 30,
//     SOLSIZEGRADIENTXMAX = 31,
//     SOLSIZEGRADIENTYMAX = 32,
//     SOLSizeGradientZMAX = 33,
//
//     //RotationOverLifetime
//     ROLANGULARVELOCITYCONST = 34,
//     ROLANGULARVELOCITYCONSTSEPRARATE = 35,
//     ROLANGULARVELOCITYGRADIENT = 36,
//     ROLANGULARVELOCITYGRADIENTX = 37,
//     ROLANGULARVELOCITYGRADIENTY = 38,
//     ROLANGULARVELOCITYGRADIENTZ = 39,
//     ROLANGULARVELOCITYGRADIENTW = 40,
//     ROLANGULARVELOCITYCONSTMAX = 41,
//     ROLANGULARVELOCITYCONSTMAXSEPRARATE = 42,
//     ROLANGULARVELOCITYGRADIENTMAX = 43,
//     ROLANGULARVELOCITYGRADIENTXMAX = 44,
//     ROLANGULARVELOCITYGRADIENTYMAX = 45,
//     ROLANGULARVELOCITYGRADIENTZMAX = 46,
//     ROLANGULARVELOCITYGRADIENTWMAX = 47,
//
//     //TextureSheetAnimation
//     TEXTURESHEETANIMATIONCYCLES = 48,
//     TEXTURESHEETANIMATIONSUBUVLENGTH = 49,
//     TEXTURESHEETANIMATIONGRADIENTUVS = 50,
//     TEXTURESHEETANIMATIONGRADIENTMAXUVS = 51,
// }

declare const enum ParticleSprite3DConstant {
    WORLDPOSITION = 0,
    WORLDROTATION = 1,
    POSITIONSCALE = 4,//TODO:是否可以从2开始
    SIZESCALE = 5,
    SCALINGMODE = 6,
    GRAVITY = 7,
    THREEDSTARTROTATION = 8,
    STRETCHEDBILLBOARDLENGTHSCALE = 9,
    STRETCHEDBILLBOARDSPEEDSCALE = 10,
    SIMULATIONSPACE = 11,
    CURRENTTIME = 12,

    //VelocityOverLifetime
    VOLVELOCITYCONST = 13,
    VOLVELOCITYGRADIENTX = 14,
    VOLVELOCITYGRADIENTY = 15,
    VOLVELOCITYGRADIENTZ = 16,
    VOLVELOCITYCONSTMAX = 17,
    VOLVELOCITYGRADIENTXMAX = 18,
    VOLVELOCITYGRADIENTYMAX = 19,
    VOLVELOCITYGRADIENTZMAX = 20,
    VOLSPACETYPE = 21,

    //ColorOverLifetime
    COLOROVERLIFEGRADIENTALPHAS = 22,
    COLOROVERLIFEGRADIENTCOLORS = 23,
    MAXCOLOROVERLIFEGRADIENTALPHAS = 24,
    MAXCOLOROVERLIFEGRADIENTCOLORS = 25,

    //SizeOverLifetime
    SOLSIZEGRADIENT = 26,
    SOLSIZEGRADIENTX = 27,
    SOLSIZEGRADIENTY = 28,
    SOLSIZEGRADIENTZ = 29,
    SOLSIZEGRADIENTMAX = 30,
    SOLSIZEGRADIENTXMAX = 31,
    SOLSIZEGRADIENTYMAX = 32,
    SOLSIZEGRADIENTZMAX = 33,

    //RotationOverLifetime
    ROLANGULARVELOCITYCONST = 34,
    ROLANGULARVELOCITYCONSTSEPRARATE = 35,
    ROLANGULARVELOCITYGRADIENT = 36,
    ROLANGULARVELOCITYGRADIENTX = 37,
    ROLANGULARVELOCITYGRADIENTY = 38,
    ROLANGULARVELOCITYGRADIENTZ = 39,
    ROLANGULARVELOCITYGRADIENTW = 40,
    ROLANGULARVELOCITYCONSTMAX = 41,
    ROLANGULARVELOCITYCONSTMAXSEPRARATE = 42,
    ROLANGULARVELOCITYGRADIENTMAX = 43,
    ROLANGULARVELOCITYGRADIENTXMAX = 44,
    ROLANGULARVELOCITYGRADIENTYMAX = 45,
    ROLANGULARVELOCITYGRADIENTZMAX = 46,
    ROLANGULARVELOCITYGRADIENTWMAX = 47,

    //TextureSheetAnimation
    TEXTURESHEETANIMATIONCYCLES = 48,
    TEXTURESHEETANIMATIONSUBUVLENGTH = 49,
    TEXTURESHEETANIMATIONGRADIENTUVS = 50,
    TEXTURESHEETANIMATIONGRADIENTMAXUVS = 51,
}

declare const enum RenderModeConstant {
    /**渲染状态_不透明。*/
    RENDERMODE_OPAQUE = 1,
    /**渲染状态_不透明_双面。*/
    RENDERMODE_OPAQUEDOUBLEFACE = 2,
    /**渲染状态_透明测试。*/
    RENDERMODE_CUTOUT = 3,
    /**渲染状态_透明测试_双面。*/
    RENDERMODE_CUTOUTDOUBLEFACE = 4,
    /**渲染状态_只读深度_透明混合。*/
    RENDERMODE_DEPTHREAD_TRANSPARENT = 5,
    /**渲染状态_只读深度_透明混合_双面。*/
    RENDERMODE_DEPTHREAD_TRANSPARENTDOUBLEFACE = 6,
    /**渲染状态_只读深度_加色法混合。*/
    RENDERMODE_DEPTHREAD_ADDTIVE = 7,
    /**渲染状态_只读深度_加色法混合_双面。*/
    RENDERMODE_DEPTHREAD_ADDTIVEDOUBLEFACE = 8,
    /**渲染状态_无深度_透明混合。*/
    RENDERMODE_NONDEPTH_TRANSPARENT = 9,
    /**渲染状态_无深度_透明混合_双面。*/
    RENDERMODE_NONDEPTH_TRANSPARENTDOUBLEFACE = 10,
    /**渲染状态_无深度_加色法混合。*/
    RENDERMODE_NONDEPTH_ADDTIVE = 11,
    /**渲染状态_无深度_加色法混合_双面。*/
    RENDERMODE_NONDEPTH_ADDTIVEDOUBLEFACE = 12,
    /**渲染状态_透明混合。*/
    RENDERMODE_TRANSPARENT = 13,
    /**渲染状态_透明混合_双面。*/
    RENDERMODE_TRANSPARENTDOUBLEFACE = 14,
    /**渲染状态_加色法混合。*/
    RENDERMODE_ADDTIVE = 15,
    /**渲染状态_加色法混合_双面。*/
    RENDERMODE_ADDTIVEDOUBLEFACE = 16,
}

declare const enum MeshType {
    BILLBOARD = 0,
    STRETCHEDBILLBOARD = 1,
    HORIZONTALBILLBOARD = 2,
    VERTICALBILLBOARD = 3,
    MESH = 4
}